# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('path', models.FileField(upload_to=b'videos/%Y/%m/%d/')),
                ('duration', models.FloatField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
