# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(upload_to='videos/%Y/%m/%d'),
        ),
    ]
