# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videochat', '0002_auto_20161024_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlyWatching', models.BooleanField(default=False)),
                ('image', models.ImageField(default='images/none/default.png', upload_to='images/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videochat.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seen',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videochat.Video'),
        ),
        migrations.AddField(
            model_name='profile',
            name='videoHistory',
            field=models.ManyToManyField(through='videochat.Seen', to='videochat.Video'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videochat.Video'),
        ),
    ]
